### ISSUE TITLE
[bug] 2.3.0版本出现无法放置方块的问题

### ISSUE THREAD

**Issue by mlbhc** [mouse0w0/law#1]
核心: Mohist 1.20.1-516

插件版本: Law 2.3.0

问题: 可以破坏方块但无法放置方块,放置后迅速消失并回到手里

global.yml

`prevent-entity-spawn: []
prevent-entity-teleport-by-portal: true
prevent-entity-explosion: [PRIMED_TNT, MINECART_TNT]
prevent-entity-break-block: [CREEPER, PRIMED_TNT, ENDER_CRYSTAL, WITHER, WITHER_SKULL, FIREBALL, SMALL_FIREBALL, MINECART_TNT, ENDERMAN]
prevent-entity-enter-vehicle: []
prevent-entity-pickup-item: []
prevent-entity-damage:
prevent-entity-damage-by-entity:
prevent-villager-to-witch: true
prevent-villager-infection: false
prevent-villager-cure: false
prevent-zombie-drowning: false
prevent-creeper-charge: false
prevent-pig-to-zombie-pigman: true
prevent-mooshroom-switch: false
prevent-fire-spread: true
prevent-fire-burn: true
prevent-fire-fade: false
prevent-snow-form: false
prevent-snowman-generate-snow: false
prevent-snow-melt: false
prevent-ice-form: true
prevent-ice-melt: false
prevent-coral-death: false
prevent-turtle-egg-trampling: true
prevent-farmland-decay: true
prevent-leaves-decay: false
prevent-dragon-egg-teleport: true
prevent-bed-explosion: true
prevent-respawn-anchor-explosion: true
prevent-water-flow: false
prevent-lava-flow: false
keep-inventory-on-death: true
keep-exp-on-death: true
disable-weather-raining: false
disable-weather-thunder: false
disable-weather-lightning: false
prevent-place-block: []
prevent-break-block: []
prevent-left-click-block: []
prevent-right-click-block: []
prevent-left-click-entity: []
prevent-right-click-entity: []
prevent-ignite-block: []`

**Comment by mouse0w0** [comment]
尝试修复了本问题，如有问题请继续在本issue下回复。

**Comment by mlbhc** [comment]
实测问题已修复,谢谢
